"""add foreign keys and indices to log tables

Revision ID: 7338129d09d5
Revises: fc5a9ee2b1fb
Create Date: 2026-05-31 11:27:30.936333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7338129d09d5'
down_revision: Union[str, Sequence[str], None] = 'fc5a9ee2b1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_log_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('job_start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('job_end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    schema='skinsense'
    )
    op.create_index('idx_job_log_job_id', 'job_log_details', ['job_id'], unique=False, schema='skinsense')
    op.create_table('event_log_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['skinsense.job_log_details.job_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skinsense'
    )
    op.create_index('idx_event_log_job_id', 'event_log_details', ['job_id'], unique=False, schema='skinsense')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_log_job_id', table_name='event_log_details', schema='skinsense')
    op.drop_table('event_log_details', schema='skinsense')
    op.drop_index('idx_job_log_job_id', table_name='job_log_details', schema='skinsense')
    op.drop_table('job_log_details', schema='skinsense')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_listing_detail', schema='skinsense')
    op.drop_table('item_day_sale', schema='skinsense')
    op.drop_table('item_day_listing', schema='skinsense')
    op.drop_index('idx_event_log_job_id', table_name='event_log_details', schema='skinsense')
    op.drop_table('event_log_details', schema='skinsense')
    op.drop_index('idx_job_log_job_id', table_name='job_log_details', schema='skinsense')
    op.drop_table('job_log_details', schema='skinsense')
    op.drop_table('item_master', schema='skinsense')
    op.drop_table('datasource', schema='skinsense')
    op.drop_table('csfloat_listing_detail', schema='skinsense')
    op.drop_table('csfloat_listing', schema='skinsense')
    # ### end Alembic commands ###
