"""drop feed_loader_log table

Revision ID: ee00c3dfb27a
Revises: 7338129d09d5
Create Date: 2026-05-31 14:21:01.038456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee00c3dfb27a'
down_revision: Union[str, Sequence[str], None] = '7338129d09d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('feed_loader_log', schema='skinsense')

def downgrade() -> None:
    """Downgrade schema."""
    op.create_table('feed_loader_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jobid', sa.String(), nullable=True),
    sa.Column('datasource_id', sa.String(), nullable=True),
    sa.Column('feed_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('time_logged', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='skinsense'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_listing_detail', schema='skinsense')
    op.drop_table('item_day_sale', schema='skinsense')
    op.drop_table('item_day_listing', schema='skinsense')
    op.drop_index('idx_event_log_job_id', table_name='event_log_details', schema='skinsense')
    op.drop_table('event_log_details', schema='skinsense')
    op.drop_index('idx_job_log_job_id', table_name='job_log_details', schema='skinsense')
    op.drop_table('job_log_details', schema='skinsense')
    op.drop_table('item_master', schema='skinsense')
    op.drop_table('datasource', schema='skinsense')
    op.drop_table('csfloat_listing_detail', schema='skinsense')
    op.drop_table('csfloat_listing', schema='skinsense')
    # ### end Alembic commands ###
