"""Initial migration

Revision ID: fc5a9ee2b1fb
Revises: 
Create Date: 2026-05-25 20:27:13.601857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5a9ee2b1fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csfloat_listing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='skinsense'
    )
    op.create_table('csfloat_listing_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('listing_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('min_offer_price', sa.Integer(), nullable=True),
    sa.Column('max_offer_discount', sa.Integer(), nullable=True),
    sa.Column('is_watchlisted', sa.Boolean(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('seller', sa.JSON(), nullable=True),
    sa.Column('item', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='skinsense'
    )
    op.create_table('datasource',
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('datasource_id'),
    schema='skinsense'
    )
    op.create_table('feed_loader_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jobid', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('time_logged', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='skinsense'
    )
    op.create_table('item_master',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('wear', sa.String(), nullable=True),
    sa.Column('stat_track', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    schema='skinsense'
    )
    op.create_table('item_day_listing',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('listings_count', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['skinsense.datasource.datasource_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['skinsense.item_master.item_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'datasource_id', 'day'),
    schema='skinsense'
    )
    op.create_table('item_day_sale',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['skinsense.datasource.datasource_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['skinsense.item_master.item_id'], ),
    sa.PrimaryKeyConstraint('item_id', 'datasource_id', 'day'),
    schema='skinsense'
    )
    op.create_table('item_listing_detail',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('datasource_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('listing_created_ts', sa.DateTime(), nullable=True),
    sa.Column('listing_type', sa.String(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('def_index', sa.Integer(), nullable=True),
    sa.Column('paint_index', sa.Integer(), nullable=True),
    sa.Column('paint_seed', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('is_stattrak', sa.Boolean(), nullable=True),
    sa.Column('is_souvenir', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['skinsense.datasource.datasource_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['skinsense.item_master.item_id'], ),
    sa.PrimaryKeyConstraint('listing_id'),
    schema='skinsense'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_listing_detail', schema='skinsense')
    op.drop_table('item_day_sale', schema='skinsense')
    op.drop_table('item_day_listing', schema='skinsense')
    op.drop_table('item_master', schema='skinsense')
    op.drop_table('feed_loader_log', schema='skinsense')
    op.drop_table('datasource', schema='skinsense')
    op.drop_table('csfloat_listing_detail', schema='skinsense')
    op.drop_table('csfloat_listing', schema='skinsense')
    # ### end Alembic commands ###
